name: Update Data

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  fetch-data:
    name: Fetch Data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Run script
        run: 'bun run data:fetch'
      - name: Commit changes
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add releases-full-data.csv
          git add releases-weekly-data.csv
          git add plugin-data.zip
          git add theme-data.json
          git commit -m "[auto] Update data" || true
          git push
